### ISSUE TITLE
No scroll bar when editing a mission's description

### ISSUE THREAD

**Issue by EM-Creations** [Global-Conflicts-ArmA/global-conflicts-site#27]
When modifying a mission's description there's no scroll bar, so if your screen isn't big enough to display the form you're bang out of luck.

![No scroll bar](https://user-images.githubusercontent.com/8123733/120903706-9a5da600-c63f-11eb-9687-1f9b8d2c72ef.png)

**Comment by VyMajoris** [comment]
Fixed.
