### ISSUE TITLE
You're able to vote on as many missions as you want via editing the disabled attribute of the voting buttons

### ISSUE THREAD

**Issue by EM-Creations** [Global-Conflicts-ArmA/global-conflicts-site#35]
As per the title, it is possible to vote on as many missions as you want by editing the disabled attribute of voting buttons, despite having used all votes.

**Before modifying:**
![image](https://user-images.githubusercontent.com/8123733/125178200-67787600-e1da-11eb-8667-cc4159765734.png)

**After removing disabled attributes from the button:**
![image](https://user-images.githubusercontent.com/8123733/125178207-84ad4480-e1da-11eb-90d4-3cf9a43e1839.png)

**Application allowing this to then happen after clicking the button:**
![image](https://user-images.githubusercontent.com/8123733/125178213-95f65100-e1da-11eb-936b-c57ec25921ac.png)

You need back-end checks as well as front-end validation as to how many votes a user has remaining.

**Comment by VyMajoris** [comment]
Fixed. The backend would not compute the vote because the amount of votes are being counted as the length of an set containing the IDs of those who voted.
